### ISSUE TITLE
Nuget package is not up to date

### ISSUE THREAD

**Issue by vinodsantharam** [GuillaumeSalles/redux.NET#2]
Hi,

The source code of the Store contains the operation "StartWith" in the construction of the observable.
But after decompiling the source code of the nuget package, it seems that the package is not up to date (StartWith operation is missing).

Vinod

**Comment by GuillaumeSalles** [comment]
Hi Vinod,

Nice catch ! I forgot to push the last version to nuget...
The version 0.2.0 will push the initial state to observers.

Thank you for your interest in Redux.NET !  :+1:

**Comment by wbuchwalter** [comment]
Je vais vous poser....
