### ISSUE TITLE
Dev tools seem restricted to universal apps

### ISSUE THREAD

**Issue by theor** [GuillaumeSalles/redux.NET#24]
Seems there's no way to use them with WPF.

**Comment by GuillaumeSalles** [comment]
Hello Theor,

Exact, it's only available for universal right now. 

I started a pull request to make devtools available for WPF. (https://github.com/GuillaumeSalles/redux.NET/pull/25). I need to fix a nuget issue first, but it should be released in the 0.3.0 package today or tomorrow.

**Comment by theor** [comment]
Excellent ! thank you.

**Comment by GuillaumeSalles** [comment]
Theor,

I updated the Redux.NET and Redux.NET.Devtools package to 0.3.0. The dev tools contains a TimeMachine WPF usercontrol. It work pretty much like the DevFrame. I didn't have any time to spend on styling, so maybe your will find it ugly... The devtools 0.4.0 will support custom styling.

Feel free to ask me anything about the new release if you have some trouble with it ! I'll update the README later this week.

Thanks

**Comment by theor** [comment]
Nice, thank you !
