### ISSUE TITLE
Hard versioned Rx-Main dependency

### ISSUE THREAD

**Issue by Maarten88** [GuillaumeSalles/redux.NET#37]
All Rx-\* packages seem to have been [unlisted from nuget](https://www.nuget.org/packages/Rx-Main/). They have been succeeded by new NETCore compatible versions and renamed as [System.Reactive](https://www.nuget.org/packages/System.Reactive/), version 3.0.0

Redux.NET has a hard nuget dependency on Rx-Main 2.2.5, causing a compile error after trying to migrate to the new version.

**Comment by GuillaumeSalles** [comment]
Sorry for not replying sooner...

I just pushed a new version of Redux.NET that depend on System.Reactive. You can find it here : https://www.nuget.org/packages/Redux.NET/1.0.1
