### ISSUE TITLE
What is the point of this Redux.NET line

### ISSUE THREAD

**Issue by cmeeren** [GuillaumeSalles/redux.NET#49]
What is the point of [this line](https://github.com/GuillaumeSalles/redux.NET/blob/abf984ef78a2034ce08729bf6042100438649faf/src/Redux/Store.cs#L33)? I.e., what is the point of calling `_stateSubject.OnNext(_lastState);` at the end of the `Store` constructor? My understanding is that it calls any subscriber callbacks (like firing an event). However, I assume it's not possible for anyone to subscribe to the `Store` before the constructor has finished, so I can't see how it's doing anything.

**Comment by GuillaumeSalles** [comment]
If you remove this line, the initial state will not be pushed at first subscription.

If I remember correctly, this [test ](https://github.com/GuillaumeSalles/redux.NET/blob/master/src/Redux.Tests/StoreTests.cs#L87) will fail if you remove it.

**Comment by GuillaumeSalles** [comment]
Maybe I'll push a new version without the Subject to clarify the code, if some people are interested.

**Comment by cmeeren** [comment]
Ah, I see, it has to do with the workings of the reactive stuff. Thanks!
