### ISSUE TITLE
Is this Dead project & no longer being maintenance?

### ISSUE THREAD

**Issue by hoangdovan** [GuillaumeSalles/redux.NET#72]
It's too long, there is no more new information...

**Comment by john-varga** [comment]
yes, the official owner of the project has stated he has no time or interest in maintaining the project anymore. a few people have expressed minor interest in taking over the project, if you would be willing to participate in that you are welcome to comment on the other issue: #69

luckily redux is simple enough that it doesn't actually require a ton of maintenance, this library works perfectly for me, I am even using it in a production app for a critical component, one that gets thousands of usages every day, and I've never had a problem with it. so as far as stability goes this lib is fine, but it's not currently maintained.

**Comment by hoangdovan** [comment]
OK. I see. Thanks!
